### ISSUE TITLE
another easy seo suggestions

### ISSUE THREAD

**Issue by robertpateii** [evangipson/midio#30]
## Expected Behavior
Your keywords "midio" generative and whatever else you want should be link text for links to midio from this github project. 

## Actual Behavior

The only link to the midio page has no link text.

## Suggested Solution
Add your usual link text to the read me and project description.

## Specifications
- Midio Version:
- Related Pull Request:

**Comment by evangipson** [comment]
Your comment inspired me to give the entire README a pass (it was pretty thin, given how feature-dense midio is), and I believe I've made lots of good improvements there, including filling out some good link text at the top of the readme. Check it out: https://github.com/evangipson/midio/commit/deb7247dcf1e18c358c493010059d908e9547e97

Do you think I still need a link in the project description? I feel like the link at the top of the README is bigger and linking it again right underneath is unnecessary.

**Comment by robertpateii** [comment]
The link at the top does not have link text though. If it did that'd prob be fine.

**Comment by robertpateii** [comment]
Nice description of it

**Comment by evangipson** [comment]
Closing this because I'm pretty sure I changed everything I could. Re-open this if I misunderstood, please!
